[package]
name = "mintymacks"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
rand = "0.9.2"
stats_alloc = "0.1.10"
mio = { version = "1.0.4", features = [ "os-ext" ] }
nix = { version = "0.30.1", features = [ "fs" ] }